language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
  - yarn docs:build
deploy:
  edge: true
  provider: pages
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  # keep_history: true
  on:
    branch: master