import { expect, test } from '@playwright/test'

test('playground can play, pause, seek, and return control to the pointer', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/showcase/')
  const player = page.getByRole('region', { name: '景深动画播放器' })
  const slider = page.getByRole('slider', { name: '景深动画进度' })
  await player.getByRole('button', { name: '播放景深动画' }).click()
  await expect.poll(async () => Number(await slider.inputValue())).toBeGreaterThan(.2)
  await player.getByRole('button', { name: '暂停动画' }).click()
  const time = await slider.inputValue()
  await page.waitForTimeout(150)
  expect(await slider.inputValue()).toBe(time)
  await slider.fill('2')
  await expect(slider).toHaveValue('2')
  const layers = await page.locator('[data-dashboard] [data-depth]').evaluateAll(nodes => nodes.map(el => Number.parseFloat((el as HTMLElement).style.getPropertyValue('--ak-layer-x'))))
  expect(layers.some(x => x > 0)).toBe(true)
  expect(layers.some(x => x < 0)).toBe(true)
  const before = await page.locator('.ak-dashboard__character-layer').getAttribute('style')
  await page.locator('[data-dashboard]').dispatchEvent('pointerleave')
  expect(await page.locator('.ak-dashboard__character-layer').getAttribute('style')).toBe(before)
  // Resource suffixes are authored only in the interface, not in either art layer.
  await expect(page.locator('.ak-counter__suffix use[href="#icon-add-circle-fill"]')).toHaveCount(2)
  await expect(page.locator('.ak-dashboard__background-layer use,.ak-dashboard__character-layer use')).toHaveCount(0)
  await player.getByRole('checkbox', { name: '循环播放' }).uncheck()
  await slider.fill('7.99')
  await player.getByRole('button', { name: '播放景深动画' }).click()
  await expect(slider).toHaveValue('8')
  await expect(player.getByRole('button', { name: '播放景深动画' })).toBeVisible()
  await player.getByRole('checkbox', { name: '循环播放' }).check()
  await player.getByRole('button', { name: '播放景深动画' }).click()
  await expect.poll(async () => Number(await slider.inputValue())).toBeGreaterThan(.1)
  await player.getByRole('button', { name: '返回指针模式' }).click()
  await expect(slider).toHaveValue('0')
  await expect.poll(() => page.locator('.ak-dashboard__character').evaluate(el => (el as HTMLElement).style.scale)).toBe('')
  await player.getByRole('button', { name: '播放景深动画' }).click()
  await expect.poll(async () => Number(await slider.inputValue())).toBeGreaterThan(.1)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(player.getByRole('button', { name: '播放景深动画' })).toBeDisabled()
  await expect(slider).toHaveValue('0')
  await expect.poll(() => page.locator('.ak-dashboard__character').evaluate(el => (el as HTMLElement).style.scale)).toBe('')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await player.getByRole('button', { name: '播放景深动画' }).click()
  await page.goto('/components/')
  await expect(page.locator('h1')).toHaveText('组件与 Playground')
  expect(errors).toEqual([])
})

test('shared slider supports keyboard bounds, fractional steps and disabled input', async ({ page }) => {
  await page.goto('/showcase/')
  const slider = page.getByRole('slider', { name: '景深动画进度' })
  await slider.focus()
  await page.keyboard.press('End')
  await expect(slider).toHaveValue('8')
  await page.keyboard.press('Home')
  await expect(slider).toHaveValue('0')
  await page.keyboard.press('ArrowRight')
  await expect(slider).toHaveValue('0.01')
  await expect(slider).toHaveCSS('--ak-slider-fill', '0.125%')

  await page.locator('.depth-controls summary').click()
  const strength = page.getByRole('slider', { name: '人物层强度' })
  await strength.fill('0.075')
  await strength.focus()
  await page.keyboard.press('ArrowRight')
  await expect(strength).toHaveValue('0.08')
  await expect(page.locator('.depth-controls__field').filter({ has: strength }).locator('output')).toHaveText('0.08')

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(slider).toBeDisabled()
  await expect(slider).toHaveValue('0')
})
