import { expect, test } from '@playwright/test'

test('section navigation synchronizes history, focus, keyboard and native wheel input', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/showcase/website')
  const root = page.locator('.ak-site')
  await expect(root).toHaveAttribute('data-ak-sections', 'ready')
  const nav = page.getByRole('navigation', { name: '章节导航', exact: true })
  await nav.getByRole('link', { name: '档案' }).click()
  await expect(page).toHaveURL(/#archive$/)
  await expect(page.locator('#archive-title')).toBeFocused()
  await expect(nav.getByRole('link', { name: '档案' })).toHaveAttribute('aria-current', 'location')
  await page.goBack()
  await expect(page.locator('#overview')).toHaveAttribute('data-active', 'true')
  await page.goForward()
  await expect(page.locator('#archive')).toHaveAttribute('data-active', 'true')
  const viewport = page.locator('[data-ak-section-viewport]')
  await viewport.focus()
  await page.keyboard.press('End')
  await expect(page).toHaveURL(/#resources$/)
  await expect(viewport).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page).toHaveURL(/#overview$/)
  // Start a transition, then native wheel input must interrupt it.
  await nav.getByRole('link', { name: '更多' }).click()
  await viewport.hover({ position: { x: 10, y: 10 } })
  await page.mouse.wheel(0, 400)
  await expect(root).not.toHaveAttribute('data-ak-navigating')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await nav.getByRole('link', { name: '情报' }).click()
  await expect(page).toHaveURL(/#updates$/)
  await expect(page.locator('[data-ak-section-current]')).toHaveText('02')
  expect(errors).toEqual([])
})

test('portrait menu traps focus, closes with Escape/link, and releases desktop modal state', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/showcase/website')
  const trigger = page.getByRole('button', { name: '打开菜单', exact: true })
  await trigger.click()
  const menu = page.getByRole('dialog', { name: '打开菜单', exact: true })
  await expect(menu).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(menu.getByRole('button', { name: '关闭菜单' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  expect(await menu.evaluate(el => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await menu.getByRole('link', { name: /档案/ }).click()
  await expect(menu).not.toBeVisible()
  await expect(page).toHaveURL(/#archive$/)
  await expect(page.locator('#archive-title')).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await trigger.click()
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect(menu).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.style.overflow)).not.toBe('hidden')
})

test('gallery selection, focus and native image dialog work together', async ({ page }) => {
  await page.goto('/showcase/website')
  await expect(page.locator('.ak-site')).toHaveAttribute('data-ak-sections', 'ready')
  // Finish intentional navigation before testing keyboard focus. VitePress also
  // focuses a deep-link target after initial hydration, independently of the gallery.
  await page.getByRole('navigation', { name: '章节导航', exact: true }).getByRole('link', { name: '档案' }).click()
  await expect(page.locator('#archive-title')).toBeFocused()
  const gallery = page.locator('.ak-gallery[aria-label="计划档案"]')
  await expect(gallery).toHaveAttribute('data-ak-gallery', 'ready')
  await gallery.getByRole('button', { name: '信标计划', exact: true }).press('ArrowRight')
  await expect(gallery.getByRole('button', { name: '地形观测', exact: true })).toBeFocused()
  await expect(gallery.getByRole('heading', { name: '地形观测' })).toBeVisible()
  await expect(gallery.locator('[data-ak-gallery-current]')).toHaveText('2 / 3')
  await gallery.getByRole('button', { name: '查看大图', exact: true }).click()
  const modal = gallery.getByRole('dialog')
  await expect(modal).toBeVisible()
  await expect(modal.locator('img')).toHaveAttribute('alt', /地形/)
  await page.keyboard.press('Escape')
  await expect(modal).not.toBeVisible()
  await expect(gallery.getByRole('button', { name: '查看大图', exact: true })).toBeFocused()
})

test('resource failures stay errors until a successful retry', async ({ page }) => {
  let failed = true
  await page.route('**/examples/site/terrain.svg', route => failed ? route.fulfill({ status: 503, body: 'unavailable' }) : route.continue())
  await page.goto('/showcase/website#resources')
  const loader = page.locator('.ak-asset-loader')
  await expect(loader).toHaveAttribute('data-state', 'error')
  await expect(loader.getByRole('status')).toContainText('1 项失败')
  await expect(loader.getByRole('progressbar')).toHaveAttribute('value', '3')
  failed = false
  await loader.getByRole('button', { name: '重试加载' }).click()
  await expect(loader).toHaveAttribute('data-state', 'ready')
  await expect(loader.getByRole('status')).toContainText('资源已就绪')
  await expect(loader.getByRole('button', { name: '重试加载' })).toHaveCount(0)
})

test('particles pause offscreen, on demand and for live reduced-motion changes', async ({ page }) => {
  await page.goto('/showcase/website#world')
  const canvas = page.locator('.ak-particle-field')
  await expect(canvas).toHaveAttribute('data-ak-renderer', /webgl|2d|static/)
  await page.getByRole('button', { name: '2D 降级预览' }).click()
  await expect(canvas).toHaveAttribute('data-ak-renderer', '2d')
  await expect(canvas).toHaveAttribute('data-ak-motion', 'running')
  await page.getByRole('button', { name: '暂停粒子' }).click()
  await expect(canvas).toHaveAttribute('data-ak-motion', 'paused')
  await page.getByRole('button', { name: '播放粒子' }).click()
  await expect(canvas).toHaveAttribute('data-ak-motion', 'running')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(canvas).toHaveAttribute('data-ak-motion', 'paused')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(canvas).toHaveAttribute('data-ak-motion', 'running')
  await page.getByRole('navigation', { name: '章节导航', exact: true }).getByRole('link', { name: '首页' }).click()
  await expect(canvas).toHaveAttribute('data-ak-motion', 'paused')
})

test('unavailable rendering contexts preserve a visible static field', async ({ page }) => {
  await page.addInitScript(() => { HTMLCanvasElement.prototype.getContext = () => null })
  await page.goto('/showcase/website#world')
  const canvas = page.locator('.ak-particle-field')
  await expect(canvas).toHaveAttribute('data-ak-renderer', 'static')
  await expect(canvas).toHaveAttribute('data-ak-motion', 'paused')
  await expect(canvas).not.toHaveCSS('background-image', 'none')
})

test('gallery handles dynamic, single and empty items, pauses native media and disposes effects', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/__visual/site')
  const gallery = page.getByRole('region', { name: 'Dynamic gallery' })
  await expect(gallery).toHaveAttribute('data-ak-gallery', 'ready')
  await gallery.getByRole('button', { name: 'Beta', exact: true }).click()
  const audio = gallery.locator('audio')
  await audio.evaluate(async el => { el.muted = true; await el.play() })
  await expect.poll(() => audio.evaluate(el => el.paused)).toBe(false)
  await gallery.getByRole('button', { name: 'Gamma', exact: true }).click()
  await expect.poll(() => audio.evaluate(el => el.paused)).toBe(true)
  await page.getByRole('button', { name: 'Remove Beta' }).click()
  await expect(gallery.getByRole('button', { name: 'Gamma', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('Gallery model')).toHaveText('1')
  await page.getByRole('button', { name: 'Single item' }).click()
  await expect(gallery.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled()
  await expect(gallery.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Remove all' }).click()
  await expect(gallery).toHaveAttribute('data-ak-gallery', 'empty')
  await expect(gallery.getByText('No items')).toBeVisible()
  await expect(page.getByLabel('Gallery model')).toHaveText('-1')
  await expect(gallery.getByRole('button', { name: 'Expand image' })).toBeDisabled()
  await page.getByRole('button', { name: 'Restore items' }).click()
  await expect(page.getByLabel('Gallery model')).toHaveText('0')
  await expect(gallery.getByRole('heading', { name: 'Alpha' })).toBeVisible()
  const canvas = await page.locator('.ak-particle-field').elementHandle()
  const galleryElement = await gallery.elementHandle()
  await page.getByRole('button', { name: 'Toggle mounted' }).click()
  expect(await canvas!.getAttribute('data-ak-motion')).toBeNull()
  expect(await galleryElement!.getAttribute('data-ak-gallery')).toBeNull()
  await page.getByRole('button', { name: 'Toggle mounted' }).click()
  await expect(gallery).toHaveAttribute('data-ak-gallery', 'ready')
  expect(errors).toEqual([])
})

test('legacy decorative loops stop when the motion preference changes', async ({ page }) => {
  await page.goto('/__visual/site')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const selector of ['.ak-fx--glow', '.ak-fx--outline', '.ak-loading-track__runner'])
    await expect(page.locator(selector)).toHaveCSS('animation-name', 'none')
  expect(await page.locator('.ak-loading').evaluate(el => getComputedStyle(el, '::after').animationName)).toBe('none')
})

test('touch gallery swipes select horizontally without blocking vertical input', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/showcase/website#archive')
  const gallery = page.locator('#archive .ak-gallery')
  await expect(gallery).toHaveAttribute('data-ak-gallery', 'ready')
  const stage = gallery.locator('[data-ak-gallery-stage]')
  await stage.dispatchEvent('pointerdown', { pointerType: 'touch', pointerId: 1, clientX: 300, clientY: 300 })
  await stage.dispatchEvent('pointerup', { pointerType: 'touch', pointerId: 1, clientX: 80, clientY: 305 })
  await expect(gallery.locator('[data-ak-gallery-current]')).toHaveText('2 / 3')
  await stage.dispatchEvent('pointerdown', { pointerType: 'touch', pointerId: 2, clientX: 200, clientY: 100 })
  await stage.dispatchEvent('pointerup', { pointerType: 'touch', pointerId: 2, clientX: 190, clientY: 400 })
  await expect(gallery.locator('[data-ak-gallery-current]')).toHaveText('2 / 3')
  await expect(stage).toHaveCSS('touch-action', 'pan-y')
})
